### ISSUE TITLE
Unpin dependencies

### ISSUE THREAD

**Issue by frankier** [yonkornilov/opus-api#64]
Currently the setup.py includes a requirements.txt, which requires specific versions of every requirement. This causes problems when combined with other software since they could require a version range which isn't compatible with the specific version required here.

Or consider another scenario: I need a newer version of e.g. requests, then I'm stuck because this package is pinned to an older version.

This article goes into a bit more depth about why setup.py should be treated differently to requirements.txt https://caremad.io/posts/2013/07/setup-vs-requirement/

My suggestion is that the dependencies should be moved into setup.py and the version should be changed to minimum versions (using >=) rather than exact version requirements.

**Comment by yonkornilov** [comment]
Given those scenarios I think that's a great suggestion. I will read that article.

Feel free to make a PR if you get the time. Otherwise I'll try to do this when I get the chance -- probably not immediately. I will comment here if I do begin work on another branch.

**Comment by yonkornilov** [comment]
This is closed with #66. Issue #69 is going to be solved with unpinned dependencies. Thanks @frankier, for your contributions.
